ROTATING_DISTANCE = 14.0
ROTATING_DISTANCE_AV = 10.0
ROTATING_ANGLE_MIN = 6.5
ROTATING_CONST = 100.0
ROTATING_ANGULAR_SPEED = 2.0

ATACHING_DISTANCE_MIN = 5.5
ATACHING_DISTANCE_MAX = 6.0
ATACHING_ANGLE_MAX = 3.0

LINEAR_MOVING_VELOCITY = 0.00001
DISTANCE_BETWEEN_SRF_SENSORS = 22.0

VERIFICATION_ANGLE = 3.0
VERIFICATION_DISTANCE = 2.0

GRIPPER_OPEN_PRESSURE_CONST = 1.0
GRIPPER_CLOSE_PRESSURE_CONST = 0.
GRIPPER_OPEN_POSITION = 1.0
GRIPPER_CLOSE_POSITION = 0.0
