# ROTATING_DISTANCE = 14.0
# ROTATING_DISTANCE_AV = 10.0
# ROTATING_ANGLE_MIN = 6.5
ROTATING_DELTA_MIN = 100.0
ROTATING_CONST = 10.0
ROTATING_ANGULAR_SPEED = 2.0
NORMALIZED_DELTA_MAX = 0.4
NORMALIZED_DELTA_MIN = 0.4


ATACHING_DISTANCE_MIN = 250
ATACHING_DISTANCE_MAX = 200
# ATACHING_ANGLE_MAX = 3.0
MAX_INITIAL_DISTANCE = 60.0

LINEAR_MOVING_VELOCITY = 0.00001
# DISTANCE_BETWEEN_SRF_SENSORS = 22.0

# VERIFICATION_ANGLE = 3.0
VERIFICATION_DISTANCE = 2.0
POSITION_VERIFICATION_INDEX = 6.0

GRIPPER_OPEN_PRESSURE_CONST = 1.0
GRIPPER_CLOSE_PRESSURE_CONST = 0.9
GRIPPER_OPEN_POSITION = 1.0
GRIPPER_CLOSE_POSITION = 0.0
