
###### ANGLE ADJUSTMENT PARAMETERS
ROTATING_DELTA_MIN = 100.0
ROTATING_CONST = 10.0
ROTATING_ANGULAR_SPEED = 2.0
NORMALIZED_DELTA_MAX = 0.4
NORMALIZED_DELTA_MIN = 0.4

DEFAULT_MAX_ANGLE_STEP = 15.0
FULL_APP_TIMEOUT = 60.0

###### ERRORS
ERROR_LINEAR_MOVEMENT_FAILED = (5,
                'gary motion command failed')
ERROR_ROTATION_MOVEMENT_FAILED = (6,'rotation movement failed')
ERROR_APPROACH_FAILED = (4,
                'approach to tag failed')

ERROR_GRIPPER_FAILED = (7,'gripper opening failed')
ERROR_GRIPPER_ATTACHMENT_FAILED = (3,'gripper attachment failed')
ERROR_CART_NOT_ATTACHED = (2,'cart was not attached')
ERROR_TIMEOUT_REACHED = (1,f'loop timeout reached,{FULL_APP_TIMEOUT}')
ERROR_CART_NOT_ACCESSABLE = (0, 'cart is too far or not accessable,')

###### ATTACHING PARAMETERS
ATACHING_DISTANCE_MIN = 250
ATACHING_DISTANCE_MAX = 200
CART_MAX_DISTANCE = 70.0

###### LINEAR MOVING PARAMETER
MIN_LINEAR_MOVING_VELOCITY = 0.005
MAX_LINEAR_MOVING_VELOCITY = 0.1

###### VERIFICATION PARAMETER
VERIFICATION_DISTANCE = 2.5
POSITION_VERIFICATION_MAX_INDEX = 6.0


###### GRIPPER PARAMETERS
GRIPPER_OPEN_PRESSURE_CONST = 1.0
GRIPPER_CLOSE_PRESSURE_CONST = 0.9
GRIPPER_OPEN_POSITION = 1.0
GRIPPER_CLOSE_POSITION = 0.0
GRIPPER_ATTACHED_POSITION = 0.003
GRIPPER_ATTACHED_THRESHOLD = 0.02

###### PRE ATTACH  PARAMETERS
PRE_ATTACH_ANGLE = 180
PRE_ATTACH_RUTATION_SPEED = 10

###### SENSOR PARAMETERS
IR_SENSOR_ID_RIGHT = 2
IR_SENSOR_ID_LEFT = 1
SRF_SENSOR_ID_CENTER = 1

###### APPROACH PARAMETERS
MAX_ANGLE_ERROR_ALLOWED = 1
MAX_Y_ERROR_ALLOWED = 0.02
DEFAULT_FINAL_APPROACH_DISTANCE = 0.65
DEFAULT_FIRST_APPROACH_DISTANCE = 1.0



